[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
elector = "BCjKShjHXdo859DhoWVjbyZgSmC3ecjFzQ8W3BkUeqTr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/elector"]
